import type { Metadata } from 'next'
import { Open_Sans, Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/src/_components/Navbar'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200','400', '600', '800'],
})

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '800'],
})

export const metadata: Metadata = {
  title: 'WESA - Wolfinger Enterprise Solutions Architects',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black scrollbar-webkit`}>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  )
}
